#!/usr/bin/env python3
"""Geocode plant addresses using Nominatim (OpenStreetMap)."""

import csv
import time
import urllib.request
import urllib.parse
import json
import sys

ADDRESSES = [
    ("Thessaloniki Plant", "Thessaloniki,Greece"),
    ("Kamari Plant", "Kamari,Stefani,Boeotia,Central Greece,32009,Greece"),
    ("Roanoke Cement", "6071 Catawba Rd,Troutville,VA,USA"),
    ("TECO Ash Plant", "13151 Wyandotte Rd,Gibsonton,FL,33534,USA"),
    ("Lakeland Ash Plant", "3030 E. Lake Parker Dr,Lakeland,FL,33805,USA"),
    ("Crystal River Ash Plant", "15760 W. Power Line St,Crystal River,FL,34428,USA"),
    ("Brandon Shores Ash Plant", "2010 Brandon Shores Dr,Baltimore,MD,21226,USA"),
    ("Brunner Island Ash Plant", "1400 Wago Rd,York Haven,PA,17370,USA"),
    ("Longview Ash Plant", "1375 Fort Martin Road,Maidsville,WV,26541,USA"),
    ("Clifty Creek Ash Plant", "1335 Clifty Hollow Road,Madison,IN,47250,USA"),
    ("Roxboro Ash Plant", "1514 Dunnaway Rd,Semora,NC,27343,USA"),
    ("Cardinal Ash Plant", "306 County Road 7E,Brilliant,OH,43913,USA"),
    ("Roxboro Ash Plant (2)", "1514 Dunnaway Rd,Semora,NC,27343,USA"),
    ("Belews Creek Ash Plant", "3195 Pine Hall Rd,Belews Creek,NC,27009,USA"),
    ("Marshall Ash Plant", "8320 NC Highway 150 E.,Terrell,NC,28682,USA"),
    ("North Bend Ash Plant", "11021 Brower Road,North Bend,OH,45052,USA"),
    ("Zimmer Ash Plant", "1781 US Route 52,Moscow,OH,45153,USA"),
    ("Belledune Ash Plant", "1558 Main St,Belledune,NB,E8G 2M3,Canada"),
    ("Pennsuco Block Plant", "11000 NW 121st Way,Medley,FL,33178,USA"),
    ("Mangonia Block Plant", "1453 53rd Street,Mangonia Park,FL,33407,USA"),
    ("Fort Pierce Block Plant", "4199 Selvitz Road,Fort Pierce,FL,34981,USA"),
    ("Melbourne Block Plant", "2575 North Avacado Ave,Melbourne,FL,32935,USA"),
    ("Edgewater Block Plant", "200 North Flagler,Edgewater,FL,32132,USA"),
    ("Orlando Block Plant", "343 Thorpe Road,Orlando,FL,32824,USA"),
    ("Tavares Block Plant", "4405 Lake Industrial Boulevard,Tavares,FL,32778,USA"),
    ("Tampa Block Industrial Lane", "7801 Industrial Lane,Tampa,FL,33637,USA"),
    ("SW FT Myers Block Plant", "4170 Canal Street,Fort Myers,FL,33916,USA"),
    ("St Augustine Block Distr", "3657 Deerpark Blvd,Elkton,FL,32033,USA"),
    ("Jacksonville Block Distr", "6557 Greenland Road,Jacksonville,FL,32258,USA"),
    ("Ft Myers Block Distribution", "5550 Division Drive,Fort Myers,FL,33905,USA"),
    ("Clermont Block Distribution", "16375 Hartwood Marsh Road,Clermont,FL,34711,USA"),
    ("Cement Plant Elefsina", "Canellopoulou 1,Elefsis,19200,Greece"),
    ("Cement plant Thessaloniki", "6.5km Thessaloniki Road,Efkarpia,Thessaloniki,56403,Greece"),
    ("Cement plant Patra", "Arachovitika,Drepano Achaia,26504,Greece"),
    ("Cement plant Kamari", "8 km Magoula Dervenohorion,Kamari Voiotias,19600,Greece"),
    ("Pennsuco Cement Plant", "11000 NW 121 Way,Medley,FL,33178,USA"),
    ("Roanoke Cement Plant", "6071 Catawba Rd,Troutville,VA,24175,USA"),
    ("Cement Plant Zlatna Panega", "Shipka str. 2,Zlatna Panega,5760,Bulgaria"),
    ("Cement Plant Zlatna Panega (2)", "Shipka str. 2,Zlatna Panega,5760,Bulgaria"),
    ("Antea Cement Plant", "Borizane,Kruje,Albania"),
    ("TITAN Cementara Kosjeric", "Zivojina Misica 50,Kosjeric,31260,Serbia"),
    ("Cement Plant Usje", "blvd. Boris Trajkovski 94,Skopje,1000,North Macedonia"),
    ("Cement Plant Sharrcem", "280 Adem Jashari,Hani i Elezit,71510,Kosovo"),
    ("Beni Suef", "Benisuef,Egypt"),
    ("Alexandria Plant", "583 El Moaskar St., El max,Alexandria,Egypt"),
    ("Artova Cement", "Kizilca Mahallesi,Tokat,60670,Turkey"),
    ("Sultanköy", "Sultankoy,Marmaraereglisi,Tekirdag,59740,Turkey"),
    ("White Rock North Agg Plant", "18300 NW 122nd Avenue,Hialeah,FL,33018,USA"),
    ("Stewart Mining Sand", "2301 Edwards Grove Rd,Immokalee,FL,34142,USA"),
    ("Stewart Mining Ft. Pierce", "13525 Indrio Rd,Fort Pierce,FL,34945,USA"),
    ("Stewart Mining Moore Haven", "1445 Lykes Road,Moore Haven,FL,33471,USA"),
    ("Lehigh Cement Terminal", "675 Quaker Hill Rd,Union Bridge,MD,21791,USA"),
    ("Central Offices Titan International", "Nicocia,Cyprus"),
    ("Central Offices Titan Greece", "Halkidos Str. 22A,Athens,11143,Greece"),
    ("Central Offices Interbeton", "Chalkidos Str. 22A,Athens,11143,Greece"),
    ("RMC Offices Achaia", "Electra 13,Patra,26333,Greece"),
    ("RMC Offices Korinthos", "Korinthos,20131,Greece"),
    ("RMC Offices Volos", "Borel 8,Volos,38333,Greece"),
    ("Tithys", "Nicosia,Cyprus"),
    ("Titan Group Finance", "12 Shed K. George Dock,Hull,HU9 5PR,UK"),
    ("Intertitan Emporiki", "Halkidos 22A,11143,Athens,Greece"),
    ("Titan Atlantic Cement", "Halkidos 22A,11143,Athens,Greece"),
    ("SIGMA BETON S.A.", "Halkidos 22A,11143,Athens,Greece"),
    ("BUSINESS PARK TITAN ELEFSINAS", "Halkidos 22A,11143,Athens,Greece"),
    ("Central Offices Intermix", "Halkidos Str. 22A,Athens,11143,Greece"),
    ("Deerfield Beach", "800 Fairway Drive,Deerfield Beach,FL,33441,USA"),
    ("Corporate Office", "5700 Lake Wright Dr,Norfolk,VA,23502,USA"),
    ("TMA Office", "188 Summerfield,Roanoke,VA,24019,USA"),
    ("S&W Administrative Office", "217 Lisbon Street,Clinton,NC,28328,USA"),
    ("Home Office", "5700 Lake Wright Dr,Norfolk,VA,23502,USA"),
    ("Carolinas Cement Company", "4312 Henson Dr,Wilmington,NC,28405,USA"),
    ("Keystone Cement Head Office", "6507 Nor Bath Blvd,Bath,PA,18014,USA"),
    ("Central Offices Zlatna Panega", "Cherni vrah bul. 33E,Sofia,Bulgaria"),
    ("Central Offices GSBP", "Cherni vrah bul. 33E,Sofia,Bulgaria"),
    ("Central Offices ANTEA", "Rruga e Durresit,Tirane,Albania"),
    ("Central Offices TCKJ", "Zivojina Misica 50,Kosjeric,31260,Serbia"),
    ("Central Offices Usje", "blvd. Boris Trajkovski 94,Skopje,1000,North Macedonia"),
    ("Obsolete (ID)", "ASNOM BB,Skopje,1000,North Macedonia"),
    ("Obsolete (OPALIT)", "ASNOM BB,Cesinovo,2333,North Macedonia"),
    ("Central Offices Sharrcem", "280 Adem Jashari,Hani i Elezit,71510,Kosovo"),
    ("Central Offices Cement Plus", "22A Magjist. Prishtine,Graqanica,14000,Kosovo"),
    ("Central Offices TCK Montenegro", "65A Josipa Broza Tita,Podgorica,81000,Montenegro"),
    ("Beni Suef HQ", "Mivida Business Park,Cairo,11835,Egypt"),
    ("Alexandria HQ", "50 Mivida Business Park,Cairo,Egypt"),
    ("Titan Beton RMC HQ", "Mivida Business Park,Cairo,11835,Egypt"),
    ("GAEA HQ", "Mivida Business Park,Cairo,11835,Egypt"),
    ("Adocim HQ", "Maslak Mah Dereboyu Cad,Istanbul,34398,Turkey"),
    ("Adocim Marmara HQ", "Esentepe Mahallesi,Istanbul,34398,Turkey"),
    ("Mine Altsi Crete", "Altsi Sitieis,Siteia,72300,Greece"),
    ("Mine Aridaia Thessaloniki", "Apsalos Arideas,Pella,58400,Greece"),
    ("Mine Milos Pozzolan", "Xylokeratia,Milos,84800,Greece"),
    ("Mine Aridaia (ex KTHMET)", "Aspra Chomata,Pella,58400,Greece"),
    ("Needham Technical Center", "101 Hampton Ave,Needham Heights,MA,02494,USA"),
    ("Mortars plant Elefsina", "Canellopoulou 1,Elefsis,19200,Greece"),
    ("Quarry Agrinio", "Thesi Alonaki Lepenous,Agrinio,30100,Greece"),
    ("Quarry Volos", "Thesi Ovria Velestinou,Volos,37500,Greece"),
    ("Quarry Drimos (INTERBETON)", "Thesi Nteve Karan,Oraiokastro,57200,Greece"),
    ("Quarry LATEM-Polidendri", "35 km Athinon-Markopoulou-Oropos,Polydendri,19014,Greece"),
    ("Quarry Leros", "Vathia Lagkada Xirokampos,Leros,85400,Greece"),
    ("Quarry Megalos Schinos", "Thesi Megalos Schinos,Asopia,32200,Greece"),
    ("Quarry Rethimno", "Latzimas Prinos Mylopotamou,Rethymno,74100,Greece"),
    ("Quarry Thisvi", "Thisvi Voiotias,Thiva,32010,Greece"),
    ("Quarry Tagarades", "2km EO Scholariou,Thermi,Thessaloniki,57500,Greece"),
    ("Quarry Xirorema (INTERBETON)", "Thesi Xirorema,Aspropyrgos,19300,Greece"),
    ("Quarry Zofori", "Zoforoi Pediados,Arkalochori,70006,Greece"),
    ("Quarry Xirorema (TITAN)", "Thesi Xirorema,Aspropyrgos,19300,Greece"),
    ("Quarry Drimos (TITAN)", "Thesi Nteve Karan Drymos,Oraiokastro,57200,Greece"),
    ("Quarry Artimes Patra", "Drepano,Artimes Achaias,26500,Greece"),
    ("Quarry Gournon S.A.", "Thesi dyo Gkremoi Anopoli,Heraklion Crete,71601,Greece"),
    ("Quarry Vachou", "Vachos,Viannos,Heraklion,70004,Greece"),
    ("Quarry Tanagras", "Thesi Grava,Tanagra,32009,Greece"),
    ("Laterite Mine Kaki Rachi", "Thesi Kaki Rachi,Aspropyrgos,19300,Greece"),
    ("Aggregates Materials Kalamata", "Kalamata,24150,Greece"),
    ("Quarry LATEKAT", "Amygdalea,Larisa,41500,Greece"),
    ("Quarry Thisvi (TITAN)", "Thisvi Voiotias,Thiva,32010,Greece"),
    ("Pennsuco Aggregate Plant", "11000 NW 121 Way,Medley,FL,33178,USA"),
    ("Center Sand Quarry", "16375 Hartwood Marsh Rd,Clermont,FL,34711,USA"),
    ("Corkscrew Aggregates", "21751 Corkscrew Road,Estero,FL,33928,USA"),
    ("Heard Aggregates Plant", "25230 Sussex Dr,Waverly,VA,23890,USA"),
    ("Castle Sands Plant", "1394 Sand Plant Rd,New Castle,VA,24127,USA"),
    ("Branchville Sand", "12390 Whitehead Road,Branchville,VA,23828,USA"),
    ("D. M. Conner, Inc.", "100 Lake Road,Stuarts Draft,VA,24477,USA"),
    ("TMAA Troutville Plant", "6071 Catawba Road,Troutville,VA,24175,USA"),
    ("Govrlovo Quarry", "s. Govrlevo,Skopje,1000,North Macedonia"),
    ("Pozzolan Quarry Spancevo", "ASNOM BB,Kocani,23000,North Macedonia"),
    ("Obsolete (Chesinovo Quarry)", "ASNOM BB,Cesinovo,2333,North Macedonia"),
    ("Elsaff Clay Quarry", "Giza,Egypt"),
    ("Wadi El Natrun Quarry", "Wadi El Natrun,Alexandria,Egypt"),
    ("Alexandria Gharbaniat", "Alexandria,Egypt"),
    ("Alexandria Qasimaya Quarry", "Alexandria,Egypt"),
    ("Attaqa Quarry", "Attaqa City,Suez,Egypt"),
    ("Vezirhan Pozzalona Quarry", "Vezirhan Beldesi,Bilecik,11130,Turkey"),
    ("Gypsum Quarry", "Bedirli Koyu,Sivas,58000,Turkey"),
    ("Slica Sand Quarry", "BAYAT Yildizeli,Sivas,58502,Turkey"),
    ("RMC Unit Antimachia", "Antimachia,Kos,85302,Greece"),
    ("RMC Unit Amaliada", "2nd km Amaliada - Roupaki,Amaliada,27200,Greece"),
    ("RMC Unit Achaikos", "Achaiko Achaia,25200,Greece"),
    ("RMC Unit Lamia", "2nd km Lamia - Domokos,Lamia,35100,Greece"),
    ("RMC Unit Drepano", "Thesi Gouves,Drepano Achaia,26504,Greece"),
    ("RMC Unit N. Efkarpia", "N. Efkarpia,Thessaloniki,56429,Greece"),
    ("RMC Unit Gennadios Rhodes", "Gennadio Rhodes,85109,Greece"),
    ("RMC Unit Koskinou Rhodes", "Koskinou,Ialissos Rhodes,85100,Greece"),
    ("RMC Unit Ioannina", "Ioannina Industrial Area,Ioannina,45500,Greece"),
    ("RMC Unit Kalathos Rhodes", "Kalathos Lindos,Rhodes,85102,Greece"),
    ("RMC Unit Korinthos", "4th km Korinthos Patra,Korinthos,20007,Greece"),
    ("RMC Unit Kos", "4th km Ko Chorion Road,Kos,85300,Greece"),
    ("RMC Unit Koropi", "Koropi,19400,Greece"),
    ("RMC Unit Kassandrinou", "Kassandrino,Chalkidiki,63077,Greece"),
    ("RMC Unit Malakassa", "Polidendri,Malakassa,19014,Greece"),
    ("RMC Unit Mandra", "Thesi Xeropigado Mandras,Mandra,19600,Greece"),
    ("RMC Unit Metamorphosi", "Tatoiou 219,Metamorfosi,14452,Greece"),
    ("RMC Unit Neochorouda", "12km Old National Road,Neochorouda,54500,Greece"),
    ("RMC Unit N.Flogita", "N. Flogita,Chalkidiki,63200,Greece"),
    ("RMC Unit Volos", "Ovria Velestinou,Volos,37500,Greece"),
    ("RMC Unit Redestos", "Nea Redestos,Thessaloniki,57001,Greece"),
    ("RMC Unit Heraklion", "Industrial Area Heraklion Crete,71601,Greece"),
    ("RMC Unit Sintriada", "Sintriada,Pyrgo Ilias,27131,Greece"),
    ("RMC Unit Thermi", "Ind. Area Thermi,Thessaloniki,57001,Greece"),
    ("RMC Unit Xilokastro", "Kamari Xilokastro,Xilokastro,20400,Greece"),
    ("RMC Unit Kallithea Achaia", "Thesi Koumpares,Kallithea Achaia,26500,Greece"),
    ("RMC Unit Paiania", "19km Paiania Avenue,Paiania,19002,Greece"),
    ("RMC Unit Zakinthos", "Thesi Kalamaki,Zakinthos,29100,Greece"),
    ("RMC Unit Zofori", "Zoforoi Pediados,Arkalochori,70006,Greece"),
    ("RMC Unit Rethimno", "Latzimas Prinos Mylopotamou,Rethymno,74100,Greece"),
    ("RMC Unit Lakomatos Chalkidikis", "VI. PA Lakomatos,Chalkidiki,63080,Greece"),
    ("RMC Unit Kasteli", "Kasteli Pediados,Heraklion,70006,Greece"),
    ("RMC Unit Therianou", "Skala Therianou Vrahneikon,Patra,25002,Greece"),
    ("RMC Unit Elliniko", "Elliniko,Athens,16777,Greece"),
    ("RMC Unit Kalamata", "Kalamata Industrial Area,Kalamata,24150,Greece"),
    ("RMC Skouries", "Megali Panagia,Chalkidiki,63074,Greece"),
    ("RMC Unit AIA", "Athens International Airport,Spata,19019,Greece"),
    ("Cocoa RMC Plant", "445 Cidco Road,Cocoa,FL,32926,USA"),
    ("Melbourne RMC Plant", "2575 N Avocado Ave,Melbourne,FL,32935,USA"),
    ("Okeechobee RMC Plant", "710 NE 3rd Ave,Okeechobee,FL,34972,USA"),
    ("Stuart RMC Plant", "1501 Monterey Rd Extension,Stuart,FL,34994,USA"),
    ("Vero Beach RMC Plant", "2725 Industrial Blvd,Vero Beach,FL,32960,USA"),
    ("Ft Pierce RMC Plant", "4199 Selvitz Road,Fort Pierce,FL,34981,USA"),
    ("Daytona RMC Plant", "405 Madison Ave,Daytona Beach,FL,32114,USA"),
    ("Deland RMC Plant", "407 N Spring Garden Ave,Deland,FL,32720,USA"),
    ("Eastport Road RMC Plant", "1220 Eastport Road,Jacksonville,FL,32218,USA"),
    ("Edgewater RMC Plant", "200 N Flagler,Edgewater,FL,32132,USA"),
    ("Greenland Road RMC Plant", "6557 Greenland Road,Jacksonville,FL,32258,USA"),
    ("Orange Park RMC Plant", "333-C Parkridge Ave,Orange Park,FL,32065,USA"),
    ("St Augustine RMC Plant", "154 Concourse Drive,Elkton,FL,32033,USA"),
    ("McDuff RMC Plant", "1712 McDuff Ave N,Jacksonville,FL,32254,USA"),
    ("Bunnell RMC Plant", "1701 N. State St.,Bunnell,FL,32110,USA"),
    ("Green Cove RMC Plant", "4866 Sediment Ct.,Green Cove Springs,FL,32043,USA"),
    ("Delray Beach RMC Plant", "1300 S Swinton Ave,Delray Beach,FL,33444,USA"),
    ("Mangonia RMC Plant", "1453 53rd Street,Mangonia Park,FL,33407,USA"),
    ("Fairgrounds RMC Plant", "9151 Weisman Way,Royal Palm Beach,FL,33411,USA"),
    ("Buena Vista RMC Plant", "1801 NW Miami Ct,Miami,FL,33136,USA"),
    ("Ft Lauderdale RMC Plant", "2500 SW 2nd Ave,Fort Lauderdale,FL,33315,USA"),
    ("North Miami RMC Plant", "290 NW 171st Street,North Miami,FL,33169,USA"),
    ("Pennsuco RMC Plant", "11955 NW 102nd Road,Medley,FL,33178,USA"),
    ("Pompano RMC Plant", "1385 Hammondville Road,Pompano Beach,FL,33069,USA"),
    ("South Miami RMC Plant", "7355 SW 48th Street,Miami,FL,33155,USA"),
    ("Longwood RMC Plant", "1450 S Ronald Reagan Blvd,Longwood,FL,32750,USA"),
    ("South Orange RMC Plant", "200 Zell Drive,Orlando,FL,32824,USA"),
    ("Winter Garden RMC Plant", "100 N Hennis Rd,Winter Garden,FL,34787,USA"),
    ("Ellenton RMC Plant", "3111 17th Street E,Palmetto,FL,34221,USA"),
    ("Ft Myers RMC Plant", "4170 Canal Street,Fort Myers,FL,33916,USA"),
    ("Punta Gorda RMC Plant", "26451 Eagle Blvd,Punta Gorda,FL,33950,USA"),
    ("Plant City RMC Plant", "2004 East Dr. MLK Jr. Blvd.,Plant City,FL,33563,USA"),
    ("Ruskin RMC Plant", "515 Cameron Driggers,Ruskin,FL,33570,USA"),
    ("Tampa RMC Plant", "5353 W Tyson Ave,Tampa,FL,33611,USA"),
    ("Venice RMC Plant", "515 Gene Green Road,Nokomis,FL,34275,USA"),
    ("Greenbay RMC Plant", "4020 Sandmine,Davenport,FL,33897,USA"),
    ("Mainline RMC Plant", "8020 Mainline Parkway,Fort Myers,FL,33912,USA"),
    ("Tavares RMC Plant", "4405 Lake Industrial Boulevard,Tavares,FL,32778,USA"),
    ("Tampa Industrial Ln RMC Plant", "7801 Industrial Lane,Tampa,FL,33637,USA"),
    ("Downtown Orlando RMC Plant", "420 W. Grant Street,Orlando,FL,32806,USA"),
    ("Anderson Road RMC Plant", "7518 Anderson Road,Tampa,FL,33634,USA"),
    ("Naples RMC Plant", "3592 Shaw Blvd.,Naples,FL,34117,USA"),
    ("Zephyrhills RM Plant", "3870 Copeland Drive,Zephyrhills,FL,33542,USA"),
    ("St Cloud RM Plant", "1501 Tileston Road,Saint Cloud,FL,34771,USA"),
    ("Port of Tampa RMC", "4219 Maritime Blvd,Tampa,FL,33605,USA"),
    ("Sarasota RMC Plant", "6520 33rd ST E,Sarasota,FL,34243,USA"),
    ("Haines City RMC Plant", "4807 Jahna Sand Mine Rd,Haines City,FL,33844,USA"),
    ("Dulles RM", "22963 Concrete Plaza,Sterling,VA,20166,USA"),
    ("Centreville RM", "15718 Lee Hwy,Centreville,VA,20120,USA"),
    ("Dumfries RM", "3454 Canal Rd,Dumfries,VA,22026,USA"),
    ("Springfield RM", "6600 Electronic Dr,Springfield,VA,22151,USA"),
    ("Clear Brook RM", "1383 Brucetown Rd,Clear Brook,VA,22624,USA"),
    ("Stafford RM", "48 Powell Ln,Fredericksburg,VA,22406,USA"),
    ("Leesburg RM", "42450 Cochran Mill Rd,Leesburg,VA,20175,USA"),
    ("Front Royal RM", "399 Kelly Dr,Front Royal,VA,22630,USA"),
    ("Campostella RM", "2125 Kimball Terrace,Norfolk,VA,23504,USA"),
    ("Oceana RM", "160 Oceana Blvd,Virginia Beach,VA,23454,USA"),
    ("Port Norfolk RM", "101 Chautaqua Ave,Portsmouth,VA,23707,USA"),
    ("Rip Rap Rd RM", "317 Rip Rap Rd,Hampton,VA,23669,USA"),
    ("Suffolk RM", "1408 Holland Rd,Suffolk,VA,23434,USA"),
    ("Chesterfield RM", "3500 Warbro Rd,Midlothian,VA,23112,USA"),
    ("Petersburg RM", "26317 Simpson Rd,North Dinwiddie,VA,23803,USA"),
    ("Oakley's RM", "4441 Oakley's Ln,Richmond,VA,23231,USA"),
    ("Bryan Park RM", "4608 Racrete Rd,Richmond,VA,23230,USA"),
    ("Flat Rock RM", "2430 Batterson Rd,Powhatan,VA,23139,USA"),
    ("Clinton RM", "1395 Turkey Hwy,Clinton,NC,28328,USA"),
    ("Goldsboro RM", "624 Powell Road,Goldsboro,NC,27530,USA"),
    ("Kinston RM", "604 E. New Bern Road,Kinston,NC,28504,USA"),
    ("Wallace RM", "768 S.E. R/R Street,Wallace,NC,28466,USA"),
    ("Elizabethtown RM", "1460 Mercer Mill Road,Elizabethtown,NC,28337,USA"),
    ("Lumberton RM", "805 S. Roberts Avenue,Lumberton,NC,28358,USA"),
    ("Whiteville RM", "701 N. Whiteville Road,Whiteville,NC,28472,USA"),
    ("Fayetteville RM", "1309 S. Reilly Road,Fayetteville,NC,28314,USA"),
    ("Spring Lake RM", "545 W. Manchester Road,Spring Lake,NC,28390,USA"),
    ("Jacksonville RM", "24 E. Thompson Street,Jacksonville,NC,28540,USA"),
    ("Holly Ridge RM", "Hwy 50 East,Holly Ridge,NC,28445,USA"),
    ("Hubert RM", "3248 Freedom,Hubert,NC,28539,USA"),
    ("New Bern RM", "1300 Hwy 17 North,New Bern,NC,28560,USA"),
    ("Morehead City RM", "5161 Business Drive,Morehead City,NC,28557,USA"),
    ("Wilmington RM", "2209 Monroe Street,Wilmington,NC,28401,USA"),
    ("Supply RM", "150 Landfille Road,Bolivia,NC,28422,USA"),
    ("Burgaw RM", "3464 Hwy 117 S.,Burgaw,NC,28425,USA"),
    ("Castle Hayne RM", "5312 Holly Shelter Road,Castle Hayne,NC,28429,USA"),
    ("Southport RM", "1619 N. Howe Street,Southport,NC,28461,USA"),
    ("Little River RM", "1040 Redi-Mix Road,Little River,SC,29566,USA"),
    ("Conway RM", "130 Winyah Road,Conway,SC,29526,USA"),
    ("Murrells Inlet RM", "12414 Hwy 707,Murrells Inlet,SC,29576,USA"),
    ("Georgetown RM", "114 Ridge Street,Georgetown,SC,29440,USA"),
    ("RMC Unit Sofia Letishte", "Poruchik Nedelcho Bonchev str,Sofia,1528,Bulgaria"),
    ("RMC Unit Sofia Voenna Rampa", "Probuda str. 12,Sofia,1220,Bulgaria"),
    ("RMC Unit Sofia Vrazhdebna", "Yaladzha str., Vrazhdebna,Sofia,1839,Bulgaria"),
    ("RMC Unit Sofia Voluyak", "Voluyak,Sofia,1346,Bulgaria"),
    ("RMC Unit Plovdiv", "Bratya Bukston bul. 161,Plovdiv,4000,Bulgaria"),
    ("RMC Unit Voivodinovo", "Voivodinovo,4135,Bulgaria"),
    ("RMC Unit Veliko Tarnovo", "Nikola Gabrovski bul. 73L,Veliko Tarnovo,5000,Bulgaria"),
    ("RMC Unit Stara Zagora", "APK str.,Stara Zagora,6000,Bulgaria"),
    ("RMC Unit Usje", "blvd. Boris Trajkovski 94,Skopje,1000,North Macedonia"),
    ("RMC Rankovce", "Rankovce,1316,North Macedonia"),
    ("October Central Plant", "6th October City,Giza,Egypt"),
    ("LIEBHERR Plant 2.25 m3", "6th October City,Giza,Egypt"),
    ("MRM Plant", "6th October City,Giza,Egypt"),
    ("LIEBHERR Plant 1 m3", "6th October City,Giza,Egypt"),
    ("Artova RMC", "Kizilca Mahallesi,Tokat,60670,Turkey"),
    ("Sivas RMC", "Erzincan Karayolu,Sivas,58000,Turkey"),
    ("Tokat RMC", "Yeni Yurt Mah.,Tokat,60030,Turkey"),
    ("Çorum RMC", "Mimar Sinan Mahallesi,Corum,19000,Turkey"),
    ("Samsun RMC", "Yesiltepe Mah,Samsun,55030,Turkey"),
    ("Silver Sand - Clermont", "16375 Hartwood Marsh Rd,Clermont,FL,34711,USA"),
    ("Silver Sand - Jacksonville", "7330 Philips Highway,Jacksonville,FL,32256,USA"),
    ("S&W Hauling", "1395 Turkey Highway,Clinton,NC,28328,USA"),
    ("Distribution center Heraklion", "Linoperamata,Heraklion Crete,71500,Greece"),
    ("Jacksonville Cem & Agg Distr", "7330 Philips Highway,Jacksonville,FL,32256,USA"),
    ("Tampa Terminal", "4219 Maritime Blvd,Tampa,FL,33605,USA"),
    ("Edgewater Terminal", "200 N Flagler Ave,Edgewater,FL,32132,USA"),
    ("Orlando Cement Terminal", "410 W Kaley,Orlando,FL,32806,USA"),
    ("Melbourne Aggregate Distr", "2575 N Avocado Ave,Melbourne,FL,32935,USA"),
    ("Ft Pierce Cem & Agg Distr", "4199 Selvitz Rd,Fort Pierce,FL,34981,USA"),
    ("Port Everglades", "1850 Eller Drive,Fort Lauderdale,FL,33316,USA"),
    ("CY Tampa Aggregate Dist", "4800 Cone Road,Tampa,FL,33610,USA"),
    ("St Augustine Distr", "154 Concourse Drive,Elkton,FL,32033,USA"),
    ("Cocoa Cem & Agg Distr", "317 Rosa L Jones Drive,Cocoa,FL,32922,USA"),
    ("TECO Cement Distribution", "13151 Wyandotte Road,Gibsonton,FL,33534,USA"),
    ("Riviera Aggregate Terminal", "1490 Martin Luther King Blvd.,Riviera Beach,FL,33404,USA"),
    ("Ustone Cement Terminal", "9870 NW 117th Way,Medley,FL,33178,USA"),
    ("Pennsuco Ash Terminal", "11000 NW 121st Way,Medley,FL,33178,USA"),
    ("Tampa Ash Terminal", "4219 Maritime Blvd,Tampa,FL,33605,USA"),
    ("Ft Lauderdale Ash Terminal", "890 SW 21st Street,Fort Lauderdale,FL,33312,USA"),
    ("Cocoa Ash Terminal", "317 Rosa L Jones Drive,Cocoa,FL,32922,USA"),
    ("Bristol Cement Terminal", "10 Spurgeon Ln,Bristol,VA,24201,USA"),
    ("Richmond Cement Terminal", "2800 N. Hopkins Rd,Richmond,VA,23225,USA"),
    ("Front Royal Cement Terminal", "33 Prezanis Rd,Front Royal,VA,22630,USA"),
    ("Norfolk Cement Terminal", "1332 Priority Ln,Chesapeake,VA,23324,USA"),
    ("Winston-Salem Cement Terminal", "3651 Penn Ave,Winston Salem,NC,27105,USA"),
    ("Selma Cement Terminal", "404 E. Preston St,Selma,NC,27576,USA"),
    ("Wilmington Cement Terminal", "6411 Ideal Cement Rd,Castle Hayne,NC,28429,USA"),
    ("Charlotte Transloading", "2820 Nevada Blvd,Charlotte,NC,28273,USA"),
    ("Fuquay Varina Cement Terminal", "9029 US 401 N,Fuquay Varina,NC,27526,USA"),
    ("RCC Elizabeth Transload", "123 Dowd Avenue,Elizabeth,NJ,07206,USA"),
    ("Norfapeake Terminal LLC", "1331 Priority Lane,Chesapeake,VA,23324,USA"),
    ("Essex Cement Terminal", "182 Calcutta Rd,Newark,NJ,07114,USA"),
    ("Riverside Essex Terminal", "7900 N. Radcliffe Drive,Bristol,PA,19007,USA"),
    ("Essex Lehigh Terminal", "3938 Easton Nazareth Highway,Nazareth,PA,18064,USA"),
    ("Longview Ash Transload", "741 Lazzelle Union Road,Maidsville,WV,26541,USA"),
    ("Louisville Ash Terminal", "7550 Grade Lane,Louisville,KY,40219,USA"),
    ("Duraport Marine Terminal", "92 East 2nd Street,Bayonne,NJ,07002,USA"),
    ("Tidewater Logistics", "440 S 3rd St,Steubenville,OH,43952,USA"),
    ("Aberdeen Ash Terminal", "230 East Maple Street,Aberdeen,NC,28315,USA"),
    ("Selma Ash Terminal", "404 E. Preston Street,Selma,NC,27576,USA"),
    ("Terminal Voenna Rampa", "Probuda 12,Sofia,1220,Bulgaria"),
    ("Durres Terminal", "Pika Doganore Port,Durres,2000,Albania"),
    ("Fier Terminal", "Fier-Lushnje,Fier,9309,Albania"),
    ("Korce Terminal", "Pika Doganore Kapshtice,Korce,7000,Albania"),
    ("Saranda Terminal", "Sarande-Gjirokaster,Sarande,9700,Albania"),
    ("Tirana Terminal", "Kashar,Tirane,Albania"),
    ("Belgrade Terminal", "Beogradska 01,Belgrade,11000,Serbia"),
    ("Chesinovo Terminal", "s. Cesinovo,Kocani,North Macedonia"),
    ("Ohrid Terminal", "s.Orovnik,Ohrid,6000,North Macedonia"),
    ("Strumica Terminal", "Strumica,2400,North Macedonia"),
    ("Bitola Terminal", "Ul. Rastanska br. 28,Bitola,7000,North Macedonia"),
    ("Duhel Terminal", "Fshati Duhle,Suhareka,23000,Kosovo"),
    ("Kline Terminal", "Dollc,Kline,32000,Kosovo"),
    ("Cement Plus Terminal", "Magjist. Prishtine - Prizren,Graqanica,10500,Kosovo"),
    ("Bar Terminal", "Bescarinska zona,Bar,85000,Montenegro"),
    ("Podgorica Terminal", "65A Josipa Broza Tita,Podgorica,81000,Montenegro"),
    ("Beni Suef Port", "Alexandria Port,Alexandria,Egypt"),
    ("Alexandria Port", "Alexandria Port,Alexandria,Egypt"),
    ("Marmara Terminal", "Bahcelievler Mah Limanyolu,Tekirdag,59740,Turkey"),
    ("Samsun Terminal", "Samsun,55300,Turkey"),
    ("Sultanköy Gemlik Terminal", "Gemlik,Bursa,16600,Turkey"),
    ("Pennsuco Alternative Fuel Plnt", "11000 NW 121 Way,Medley,FL,33178,USA"),
    ("GAEA - BSF", "Beni Suef,Egypt"),
    ("GAEA - ALX", "Abis fertilizer plant,Alexandria,Egypt"),
    ("GAEA Khanka", "Qalyubiyya,Egypt"),
    ("Warehouse Evripos", "Ritsonas,Glyfa Chalkidas,34100,Greece"),
    ("Warehouse Markopoulo", "28 km Athens Lavrio,Markopoulo,19003,Greece"),
    ("Warehouse Rethymno", "Latzimas Prinos Mylopotamou,Rethymno,74100,Greece"),
    ("Warehouse Thessaloniki port", "Thessaloniki Port,Thessaloniki,54012,Greece"),
    ("Ship Elefsina", "Canellopoulou,Elefsina,19200,Greece"),
    ("Aggregates warehouse Patra", "Arachovitika,Drepano Achaia,26504,Greece"),
    ("Warehouse BIPE Irakleiou", "ΒΙΠΕ Ηρακλείου,Heraklion,71408,Greece"),
    ("Nicholson St RM", "111 N. Nicholson St,Henrico,VA,23231,USA"),
    ("National Gardens Terminal", "1080 Broadway Ave.,Ormond Beach,FL,32174,USA"),
]


def geocode(query):
    url = "https://nominatim.openstreetmap.org/search?" + urllib.parse.urlencode({
        "q": query,
        "format": "json",
        "limit": 1,
    })
    req = urllib.request.Request(url, headers={"User-Agent": "titan-geocode/1.0"})
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read())
            if data:
                return data[0]["lat"], data[0]["lon"]
    except Exception as e:
        print(f"  ERROR: {e}", file=sys.stderr)
    return "", ""


def main():
    output_file = "geocoded_addresses.csv"
    with open(output_file, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["Name", "Address", "Latitude", "Longitude"])
        total = len(ADDRESSES)
        for i, (name, address) in enumerate(ADDRESSES, 1):
            print(f"[{i}/{total}] {name} ...", end=" ", flush=True)
            lat, lon = geocode(address)
            if lat:
                print(f"{lat}, {lon}")
            else:
                print("NOT FOUND")
            writer.writerow([name, address, lat, lon])
            time.sleep(1.1)  # Nominatim requires max 1 req/sec


if __name__ == "__main__":
    main()
